services:
  axpert:
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - /dev/hidraw0:/dev/hidraw0
    working_dir: /home/axpert
    user: root
    restart: unless-stopped
    volumes:
      - ./web:/web
      - ./collect-data.sh:/app/collect-data.sh:ro
    command: bash /app/collect-data.sh
  web-server:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    depends_on:
      - axpert
    restart: unless-stopped
  # localtunnel-axpert:
  #   build:
  #     context: .
  #     dockerfile: lt.Dockerfile
  #   command: lt --port 8082 --subdomain mining-axpert-api
  #   network_mode: host
  #   depends_on:
  #     - web-server
  #   restart: unless-stopped
  tapo-api:
    image: clementnerma/tapo-rest
    ports:
      - "8081:80"
    volumes:
      - ./devices.json:/app/devices.json
  # localtunnel-tapo:
  #   build:
  #     context: .
  #     dockerfile: lt.Dockerfile
  #   command: lt --port 8081 --subdomain mining-tapo
  #   network_mode: host
  #   restart: unless-stopped
  ngrok-axpert:
    container_name: ngrok
    image: ngrok/ngrok:latest
    command: [ "http", "--url=${NGROK_STATIC_DOMAIN}", "8082" ]
    network_mode: host
    environment:
      - NGROK_AUTHTOKEN_AXPERT
      - NGROK_STATIC_DOMAIN_AXPERT
    volumes:
      - ./src:/app/src
  ngrok-tapo:
    container_name: ngrok
    image: ngrok/ngrok:latest
    command: [ "http", "--url=${NGROK_STATIC_DOMAIN}", "8081" ]
    network_mode: host
    environment:
      - NGROK_AUTHTOKEN_TAPO
      - NGROK_STATIC_DOMAIN_TAPO
    volumes:
      - ./src:/app/src